### PR TITLE
Update wiesbaden.Rmd

### PR DESCRIPTION
**Pull request by DominikVogel**
Remove the part on the genesis premium account. The genesis database can now be used with a free account (https://twitter.com/destatis/status/1523936080998932484)

### CODE REVIEW

**Comment by sumtxt** [comment]
Thank you for sharing and editing!

**Comment by DominikVogel** [comment]
Thank you for provding the package!

**Comment by DominikVogel** [comment]
Is there a way to update the doc (https://sumtxt.github.io/wiesbaden/articles/wiesbaden.html), too?

**Comment by sumtxt** [comment]
Yes, forgot about it. Fixed now.

**Pull request merged**
